---
services:
  traefik:
    image: traefik:v3.3
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    environment:
      # Your Cloudflare API Token(We're using Cloudflare to Resolve DNS)
      - CF_DNS_API_TOKEN=${CF_DNS_API_TOKEN}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config/traefik.yaml:/etc/traefik/traefik.yaml:ro
      # mount the ./data/certs to the location you have specified in the certificate resolver
      - ./data/certs:/var/traefik/certs:rw
    restart: unless-stopped
    networks:
      - proxy-network

networks:
  proxy-network:
    external: true
