global:
  checkNewVersion: false
  sendAnonymousUsage: false

log:
  level: DEBUG # [DEBUG, INFO, WARNING, ERROR, CRITICAL]
  # -- (Optional) Enable File Log
  # format: common # [common, json, logfmt]
  # filePath: /var/log/traefik/traefik.log

# -- (Optional) Enable Accesslog
# accessLog:
#   format: common # [common, json, logfmt]
#   filePath: /var/log/traefik/access.log

api:
  dashboard: true
  insecure: true

entryPoints:
  web:
    address: :80
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: :443

# enable ping so the `traefik healthcheck` works
ping: {}

tls:
  stores:
    default:
      defaultCertificate:
        certFile: "/var/traefik/certs/localhost.crt"
        keyFile: "/var/traefik/certs/localhost.key"

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
